<a href="https://colab.research.google.com/github/seanigens/IntroDataViz/blob/main/Lab2S544.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Mounted at /content/drive

In [2]:
file_path = "/content/drive/My Drive/S544/avocado-updated-2020.csv"
df = pd.read_csv(file_path)
print(df.head())

         date  average_price  total_volume       4046       4225      4770  \
0  2015-01-04           1.22      40873.28    2819.50   28287.42     49.90
1  2015-01-04           1.79       1373.95      57.42     153.88      0.00
2  2015-01-04           1.00     435021.49  364302.39   23821.16     82.15
3  2015-01-04           1.76       3846.69    1500.15     938.35      0.00
4  2015-01-04           1.08     788025.06   53987.31  552906.04  39995.03

   total_bags  small_bags  large_bags  xlarge_bags          type  year  \
0     9716.46     9186.93      529.53          0.0  conventional  2015
1     1162.65     1162.65        0.00          0.0       organic  2015
2    46815.79    16707.15    30108.64          0.0  conventional  2015
3     1408.19     1071.35      336.84          0.0       organic  2015
4   141136.68   137146.07     3990.61          0.0  conventional  2015

              geography
0                Albany
1                Albany
2               Atlanta
3               Atlanta
4  Baltimore/Washington

In [51]:
avo2020rough= pd.read_csv(file_path,
                        header=None,
                        names=[
"date","average_price", "total_volume",	"4046.00", "4225.00", "4770.00", "total_bags", "small_bags", "large_bags", "xlarge_bags", "type", "year", "geography"])
avo2020rough

,date,average_price,total_volume,4046.00,4225.00,4770.00,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography
0,date,average_price,total_volume,4046.00,4225.00,4770.00,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography
1,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
2,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.0,0.0,organic,2015,Albany
3,2015-01-04,1.0,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.0,conventional,2015,Atlanta
4,2015-01-04,1.76,3846.69,1500.15,938.35,0.00,1408.19,1071.35,336.84,0.0,organic,2015,Atlanta
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33041,2020-11-29,1.47,1583056.27,67544.48,97996.46,2617.17,1414878.1,906711.52,480191.83,27974.75,organic,2020,Total U.S.
33042,2020-11-29,0.91,5811114.22,1352877.53,589061.83,19741.90,3790665.29,2197611.02,1531530.14,61524.13,conventional,2020,West
33043,2020-11-29,1.48,289961.27,13273.75,19341.09,636.51,256709.92,122606.21,134103.71,0.0,organic,2020,West
33044,2020-11-29,0.67,822818.75,234688.01,80205.15,10543.63,497381.96,285764.11,210808.02,809.83,conventional,2020,West Tex/New Mexico
33045,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.0,organic,2020,West Tex/New Mexico

In [52]:
avo2020 = avo2020.drop(0)
avo2020

,date,average_price,total_volume,4046.00,4225.00,4770.00,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography
1,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
2,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.0,0.0,organic,2015,Albany
3,2015-01-04,1.0,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.0,conventional,2015,Atlanta
4,2015-01-04,1.76,3846.69,1500.15,938.35,0.00,1408.19,1071.35,336.84,0.0,organic,2015,Atlanta
5,2015-01-04,1.08,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.0,conventional,2015,Baltimore/Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33041,2020-11-29,1.47,1583056.27,67544.48,97996.46,2617.17,1414878.1,906711.52,480191.83,27974.75,organic,2020,Total U.S.
33042,2020-11-29,0.91,5811114.22,1352877.53,589061.83,19741.90,3790665.29,2197611.02,1531530.14,61524.13,conventional,2020,West
33043,2020-11-29,1.48,289961.27,13273.75,19341.09,636.51,256709.92,122606.21,134103.71,0.0,organic,2020,West
33044,2020-11-29,0.67,822818.75,234688.01,80205.15,10543.63,497381.96,285764.11,210808.02,809.83,conventional,2020,West Tex/New Mexico
33045,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.0,organic,2020,West Tex/New Mexico

The dataframe contains avocado sales information across various dates from different cities and regions across the U.S.

In [53]:
avo2020['date'] = pd.to_datetime(avo2020['date'])

In [56]:
avo2020['month'] = avo2020['date'].dt.month
avo2020['day'] = avo2020['date'].dt.day
avo2020['year'] = avo2020['date'].dt.year

In [59]:
avo2020

,date,average_price,total_volume,4046.00,4225.00,4770.00,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography,month,day
1,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1,4
2,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.0,0.0,organic,2015,Albany,1,4
3,2015-01-04,1.0,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.0,conventional,2015,Atlanta,1,4
4,2015-01-04,1.76,3846.69,1500.15,938.35,0.00,1408.19,1071.35,336.84,0.0,organic,2015,Atlanta,1,4
5,2015-01-04,1.08,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.0,conventional,2015,Baltimore/Washington,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33041,2020-11-29,1.47,1583056.27,67544.48,97996.46,2617.17,1414878.1,906711.52,480191.83,27974.75,organic,2020,Total U.S.,11,29
33042,2020-11-29,0.91,5811114.22,1352877.53,589061.83,19741.90,3790665.29,2197611.02,1531530.14,61524.13,conventional,2020,West,11,29
33043,2020-11-29,1.48,289961.27,13273.75,19341.09,636.51,256709.92,122606.21,134103.71,0.0,organic,2020,West,11,29
33044,2020-11-29,0.67,822818.75,234688.01,80205.15,10543.63,497381.96,285764.11,210808.02,809.83,conventional,2020,West Tex/New Mexico,11,29
33045,2020-11-29,1.35,24106.58,1236.96,617.80,1564.98,20686.84,17824.52,2862.32,0.0,organic,2020,West Tex/New Mexico,11,29

Warning: total number of rows (33045) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: total number of rows (33045) exceeds max_rows (20000). Limiting to first (20000) rows.

July sold the most avocados

In [58]:
calavo2020 = avo2020[(avo2020["geography"] == "San Francisco") | (avo2020["geography"] == "San Diego")| (avo2020["geography"] == "Los Angeles")| (avo2020["geography"] == "Sacramento")]
calavo2020

,date,average_price,total_volume,4046.00,4225.00,4770.00,total_bags,small_bags,large_bags,xlarge_bags,type,year,geography,month,day
45,2015-01-04,0.85,2682159.95,1837999.65,524430.47,64225.78,255504.05,215571.8,36981.72,2950.53,conventional,2015,Los Angeles,1,4
46,2015-01-04,1.25,54495.54,47721.51,1723.40,0.00,5050.63,5050.63,0.0,0.0,organic,2015,Los Angeles,1,4
81,2015-01-04,1.05,430138.88,110693.69,270107.61,9737.50,39600.08,39600.08,0.0,0.0,conventional,2015,Sacramento,1,4
82,2015-01-04,1.33,9213.49,3727.52,4327.52,0.00,1158.45,1158.45,0.0,0.0,organic,2015,Sacramento,1,4
83,2015-01-04,0.94,461607.33,244152.26,165299.33,15302.75,36852.99,30884.29,5595.0,373.7,conventional,2015,San Diego,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33019,2020-11-29,1.43,23531.38,3303.69,2057.03,0.00,18170.66,18144.54,26.12,0.0,organic,2020,Sacramento,11,29
33020,2020-11-29,1.12,469356.72,104509.99,19988.45,7210.47,337647.81,189341.36,127701.64,20604.81,conventional,2020,San Diego,11,29
33021,2020-11-29,1.95,25799.95,894.63,838.11,0.00,24067.21,9691.46,14375.75,0.0,organic,2020,San Diego,11,29
33022,2020-11-29,1.5,644141.37,128555.43,136718.24,5597.21,373270.49,159276.65,207760.32,6233.52,conventional,2020,San Francisco,11,29
33023,2020-11-29,1.87,59527.02,2815.23,4542.30,0.00,52169.49,52034.33,135.16,0.0,organic,2020,San Francisco,11,29

In [65]:
from plotnine import ggplot, geom_point, aes, geom_boxplot

In [ ]:
from plotnine import theme_classic
(ggplot(calavo2020, aes(x = "geography", y = "total_volume", fill = "geography"))
+ geom_boxplot()
+ theme_classic()
)

Los Angeles has sold the highest volume of avocados